project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Home"
  search: false
  # site-url: http://andreacappozzo.rbind.io
  favicon: icon.png
  # repo-url: https://github.com/andreaczhang/andreaczhang.github.io
  # repo-actions: [edit, issue]

  page-footer:
    left: "&copy;2025 Andrea Cappozzo"
    right: "Powered by [Quarto](https://quarto.org/) with the invaluable support of [qtwAcademic](https://andreaczhang.github.io/qtwAcademic/)"

  navbar:
    background: "#00315f"
    right:
      
      - href: short_bio.qmd
        text: Short Bio

      - href: publications.qmd
        text: Publications
      
      - href: teaching.qmd
        text: Teaching
      
      - href: contact.qmd
        text: Contact
      
format:
  html:
    page-layout: full
    theme: [simplex, styles_AC.css]
    # fontsize: 1.1em



